### ISSUE TITLE
Support Ubuntu 16.10

### ISSUE THREAD

**Issue by acrap** [fcwu/desktop-mirror#11]
I tried to install manually, but it is dependency hell, that begins from python-wxgtk2.8. But i can't install it because:

libwxbase2.8-0
libwxgtk-media2.8-0
libwxgtk2.8-0

**Comment by fcwu** [comment]
@acrap 
I have no plan to support Ubuntu 16.10. PR is very welcome

**Comment by acrap** [comment]
UPD:
It is my fault. I have Ubuntu 16.04, not Ubuntu 16.10.
