### ISSUE TITLE
update to ubuntu 18.04

### ISSUE THREAD

**Issue by roberto-sebastiano** [fcwu/desktop-mirror#15]
Hello,

could you please update the software to work with ubuntu 18.04 ?

It looks like the software is great but no longer updated

Thank you,
Roberto

**Comment by dcrystalj** [comment]
At least please add requirements.txt so we can build it our-self. I tried to build but im missing ton on python libs.

**Comment by roberto-sebastiano** [comment]
closing as it seems that this is not maintained anymore.
