### ISSUE TITLE
windows binary link broken

### ISSUE THREAD

**Issue by rodnet-dev** [fcwu/desktop-mirror#5]
the link on your page for the windows installer is broken https://dl.dropboxusercontent.com/u/23905041/qnap/desktop-mirror.exe
please make this available!

**Comment by horfic** [comment]
bump

**Comment by fcwu** [comment]
Update link to README.md

**Comment by sudar** [comment]
Thanks for correcting the link to the windows binary file.

A small suggestion. If possible add the instructions that are used to generate the Windows binary file to the README.md so that in future people can do their own build, if the dropbox link fails again.

**Comment by fcwu** [comment]
Check out README.md. Need someone to verify the steps.

**Comment by sudar** [comment]
@fcwu Thanks for adding the build instructions.
