### ISSUE TITLE
What is the license for the source code?

### ISSUE THREAD

**Issue by sudar** [fcwu/desktop-mirror#6]
First of all thanks for the project and also for releasing the code.

Since the project doesn't have a license file, I am just curious what is the license under which you have released this source code?

Thanks.

**Comment by fcwu** [comment]
I update the LICENSE file. desktop-mirror is under Apache 2.0.

**Comment by sudar** [comment]
Thanks :)

**Comment by horfic** [comment]
where is the license file?

**Comment by horfic** [comment]
i found in some files this

License: GPL-3
 The full text of the GPL is distributed in
 /usr/share/common-licenses/GPL-3 on Debian systems.

**Comment by fcwu** [comment]
Update to the root of source code

**Comment by sudar** [comment]
Thanks for adding the license file.

I am closing this issue since it is resolved.
